/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementportal;

import java.sql.Statement;
import java.sql.*;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandy
 */
public class addNewStudent extends javax.swing.JFrame {

    /**
     * Creates new form addNewStudent
     */
    public addNewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        addStudent = new javax.swing.JButton();
        insertResult = new javax.swing.JButton();
        regStudent = new javax.swing.JButton();
        allStudent = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        courseInput = new javax.swing.JComboBox<>();
        branchInput = new javax.swing.JComboBox<>();
        brnch = new javax.swing.JComboBox<>();
        nameInput = new javax.swing.JTextField();
        genderSelect = new javax.swing.JComboBox<>();
        fatherInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        rollNo = new javax.swing.JTextField();
        redgNo = new javax.swing.JTextField();
        yr = new javax.swing.JComboBox<>();
        nlab = new javax.swing.JLabel();
        flab = new javax.swing.JLabel();
        rlab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 10));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        addStudent.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        addStudent.setForeground(new java.awt.Color(255, 102, 102));
        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/logo/add (1).png"))); // NOI18N
        addStudent.setText("Add new Student");
        addStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        insertResult.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        insertResult.setText("Insert new result");
        insertResult.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        insertResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertResultActionPerformed(evt);
            }
        });

        regStudent.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        regStudent.setText("Registered Student");
        regStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        regStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regStudentActionPerformed(evt);
            }
        });

        allStudent.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        allStudent.setText("All Students List");
        allStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        allStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentActionPerformed(evt);
            }
        });

        logOut.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/logo/logoutlogo.png"))); // NOI18N
        logOut.setText("Log out");
        logOut.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, null));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertResult, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(logOut)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(addStudent)
                .addGap(50, 50, 50)
                .addComponent(insertResult)
                .addGap(47, 47, 47)
                .addComponent(regStudent)
                .addGap(50, 50, 50)
                .addComponent(allStudent)
                .addGap(34, 34, 34)
                .addComponent(logOut)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 710));

        jPanel4.setBackground(new java.awt.Color(242, 227, 220));
        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setText("Course");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setText("Branch Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setText("Roll Number");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setText("Name");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setText("Father's Name");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        courseInput.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        courseInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BTech", "BSc", "BCA", "MTech", "MSc", "MCA", "BBA", "MBA" }));
        jPanel4.add(courseInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        branchInput.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        branchInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mechanical", "Electrical", "E&TC", "EEE", "CSE", "Computer Application", " " }));
        branchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchInputActionPerformed(evt);
            }
        });
        jPanel4.add(branchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        brnch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        brnch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MED", "ELE", "ETC", "EEE", "CSE", "BCA", "MCA", "BSC", "MSC", "MBA", "BBA" }));
        brnch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnchActionPerformed(evt);
            }
        });
        jPanel4.add(brnch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        nameInput.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        nameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameInputKeyReleased(evt);
            }
        });
        jPanel4.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 190, -1));

        genderSelect.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        genderSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        genderSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderSelectActionPerformed(evt);
            }
        });
        jPanel4.add(genderSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 75, -1));

        fatherInput.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        fatherInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherInputActionPerformed(evt);
            }
        });
        fatherInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherInputKeyReleased(evt);
            }
        });
        jPanel4.add(fatherInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 190, -1));

        saveBtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/logo/save (1).png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel4.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 100, 30));

        rollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoActionPerformed(evt);
            }
        });
        rollNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rollNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollNoKeyTyped(evt);
            }
        });
        jPanel4.add(rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, 30));

        redgNo.setEditable(false);
        redgNo.setBackground(new java.awt.Color(242, 227, 220));
        redgNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        redgNo.setBorder(null);
        redgNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redgNoActionPerformed(evt);
            }
        });
        jPanel4.add(redgNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 240, 20));

        yr.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        yr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "19", "20", "21", "22", "23", "24" }));
        yr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrActionPerformed(evt);
            }
        });
        jPanel4.add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 54, -1));

        nlab.setForeground(new java.awt.Color(255, 0, 51));
        jPanel4.add(nlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 190, 20));

        flab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(flab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 180, 20));

        rlab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(rlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 160, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 390, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/images/schoolooffice.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        

    }//GEN-LAST:event_addStudentActionPerformed

    private void insertResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertResultActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new InsertResult().setVisible(true);

    }//GEN-LAST:event_insertResultActionPerformed

    private void regStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RegisteredStudent().setVisible(true);
    }//GEN-LAST:event_regStudentActionPerformed

    private void allStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AllStudentResult().setVisible(true);
    }//GEN-LAST:event_allStudentActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        // setVisible(false);

        int a=JOptionPane.showConfirmDialog(this, "Do You Really Want to LogOut");
        if(a==0){
            new index().setVisible(true);

        }
        else

        setVisible(true);
        //
    }//GEN-LAST:event_logOutActionPerformed

    private void branchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchInputActionPerformed

    private void brnchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_brnchActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
        
       
        
        
    }//GEN-LAST:event_nameInputActionPerformed

    private void fatherInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fatherInputActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String courses=(String)courseInput.getSelectedItem();
        String branch=(String)branchInput.getSelectedItem();
        String rollno=redgNo.getText();
        String name=nameInput.getText();
        String fathername=fatherInput.getText();
        String gender =(String)genderSelect.getSelectedItem();
        
        
        if(name.equals("")&&fathername.equals("")&&rollno.equals(""))
        {  JOptionPane.showMessageDialog(null,"Field Can't be empty");
            
        }
      else if(name.equals("")&&!fathername.equals("")&&!rollno.equals(""))
        {  JOptionPane.showMessageDialog(null,"Name Can't be empty");
            
        }
       else if(!name.equals("")&&fathername.equals("")&&!rollno.equals(""))
        {  JOptionPane.showMessageDialog(null," Father Name Can't be empty");
            
        }
        else if(!name.equals("")&&!fathername.equals("")&&rollno.equals(""))
        {  JOptionPane.showMessageDialog(null," Father Name Can't be empty");
            
        }
         else if(name.equals("")&&fathername.equals("")&&!rollno.equals(""))
        {  JOptionPane.showMessageDialog(null,"Name  and Father Name Can't be empty");
            
        }
         else if(!name.equals("")&&fathername.equals("")&&rollno.equals(""))
        {  JOptionPane.showMessageDialog(null,"Father  and Roll No Can't be empty");
            
        }
         else if(name.equals("")&&!fathername.equals("")&&!rollno.equals(""))
        {  JOptionPane.showMessageDialog(null,"Name  and Roll No Can't be empty");
            
        }
            
         else{
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","210396");
            Statement st=con.createStatement();
            st.executeUpdate("insert into student values('"+rollno+"','"+courses+"','"+branch+"','"+name+"','"+gender+"','"+fathername+"')");
            JOptionPane.showMessageDialog(null,"Sucessfully added");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        }
        
        
        

    }//GEN-LAST:event_saveBtnActionPerformed

    private void rollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rollNoActionPerformed

    private void redgNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redgNoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_redgNoActionPerformed

    private void yrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_yrActionPerformed

    private void genderSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderSelectActionPerformed

    private void fatherInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherInputKeyReleased
        String PATTERN ="[a-zA-Z](0,30)$";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(fatherInput.getText());
        if(!match.matches())
            flab.setText("Invalid name");
        else
          flab.setText("");
    }//GEN-LAST:event_fatherInputKeyReleased

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel4ComponentShown

    private void rollNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollNoKeyTyped
        // TODO add your handling code here:
        String rollNoWritten=rollNo.getText();
        if(rollNoWritten.length()<4||rollNoWritten.length()>4)
            rlab.setText("Invalid Rollno");
        else
        { rlab.setText(null);
        redgNo.setText((String)brnch.getSelectedItem()+(String)yr.getSelectedItem()+rollNoWritten);
        
        }
        
        
            
    }//GEN-LAST:event_rollNoKeyTyped

    private void nameInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameInputKeyReleased
        // TODO add your handling code here:
        String PATTERN ="[a-zA-Z](0,30)$";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(nameInput.getText());
        if(!match.matches())
            nlab.setText("Invalid name");
        else
          nlab.setText("");
    }//GEN-LAST:event_nameInputKeyReleased

    private void rollNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollNoKeyPressed
        // TODO add your handling code here:
        String PATTERN ="^[0-9](0,30)$";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(fatherInput.getText());
        if(!match.matches())
            rlab.setText("roll no should contains number");
        else
          rlab.setText("");
    }//GEN-LAST:event_rollNoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JButton allStudent;
    private javax.swing.JComboBox<String> branchInput;
    private javax.swing.JComboBox<String> brnch;
    private javax.swing.JComboBox<String> courseInput;
    private javax.swing.JTextField fatherInput;
    private javax.swing.JLabel flab;
    private javax.swing.JComboBox<String> genderSelect;
    private javax.swing.JButton insertResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nlab;
    private javax.swing.JTextField redgNo;
    private javax.swing.JButton regStudent;
    private javax.swing.JLabel rlab;
    private javax.swing.JTextField rollNo;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> yr;
    // End of variables declaration//GEN-END:variables
}
