/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementportal;

import java.sql.Statement;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandy
 */
public class InsertResult extends javax.swing.JFrame {

    /**
     * Creates new form InsertResult
     */
    public InsertResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        addStudent = new javax.swing.JButton();
        insertResult = new javax.swing.JButton();
        regStudent = new javax.swing.JButton();
        allStudent = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        subEng = new javax.swing.JTextField();
        subMath = new javax.swing.JTextField();
        subPhysics = new javax.swing.JTextField();
        subChemistry = new javax.swing.JTextField();
        subDrawing = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        saveMark = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        rollNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rlab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 10));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        addStudent.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/logo/add (1).png"))); // NOI18N
        addStudent.setText("Add new Student");
        addStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        insertResult.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        insertResult.setForeground(new java.awt.Color(255, 102, 102));
        insertResult.setText("Insert new result");
        insertResult.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        insertResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertResultActionPerformed(evt);
            }
        });

        regStudent.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        regStudent.setText("Registered Student");
        regStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        regStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regStudentActionPerformed(evt);
            }
        });

        allStudent.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        allStudent.setText("All Students List");
        allStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        allStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentActionPerformed(evt);
            }
        });

        logOut.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/logo/logoutlogo.png"))); // NOI18N
        logOut.setText("Log out");
        logOut.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, null));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertResult, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(logOut)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(addStudent)
                .addGap(50, 50, 50)
                .addComponent(insertResult)
                .addGap(47, 47, 47)
                .addComponent(regStudent)
                .addGap(50, 50, 50)
                .addComponent(allStudent)
                .addGap(34, 34, 34)
                .addComponent(logOut)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 740));

        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subEngActionPerformed(evt);
            }
        });
        subEng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subEngKeyPressed(evt);
            }
        });
        jPanel1.add(subEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 113, 111, -1));

        subMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMathActionPerformed(evt);
            }
        });
        subMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subMathKeyPressed(evt);
            }
        });
        jPanel1.add(subMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 157, 111, -1));

        subPhysics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subPhysicsKeyPressed(evt);
            }
        });
        jPanel1.add(subPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 198, 111, -1));

        subChemistry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subChemistryKeyPressed(evt);
            }
        });
        jPanel1.add(subChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 238, 111, -1));

        subDrawing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subDrawingKeyPressed(evt);
            }
        });
        jPanel1.add(subDrawing, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 281, 111, -1));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField9.setText("English");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 110, 111, -1));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField10.setText("Mathematics");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 154, 111, -1));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField11.setText("Physics");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 198, 111, -1));

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField12.setText("Chemistry");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 242, 111, -1));

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField13.setText("Engg. Drawing");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 286, 111, -1));

        saveMark.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        saveMark.setText("Save");
        saveMark.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.blue, null));
        saveMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMarkActionPerformed(evt);
            }
        });
        jPanel1.add(saveMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 130, -1));

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField16.setText("Roll no");
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 111, -1));

        rollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoActionPerformed(evt);
            }
        });
        jPanel1.add(rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 111, -1));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 140, 20));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, 20));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 110, 20));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 110, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 120, 20));

        rlab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(rlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 150, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1080, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertResultActionPerformed
        // TODO add your handling code here:
        setVisible(false);
     new InsertResult().setVisible(true);
       
    }//GEN-LAST:event_insertResultActionPerformed

    private void subMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMathActionPerformed

    private void subEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subEngActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_subEngActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void regStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
     new RegisteredStudent().setVisible(true);
    }//GEN-LAST:event_regStudentActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    new addNewStudent().setVisible(true);
    }//GEN-LAST:event_addStudentActionPerformed

    private void allStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentActionPerformed
        // TODO add your handling code here:
         setVisible(false);
     new AllStudentResult().setVisible(true);
    }//GEN-LAST:event_allStudentActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(this, "Do You Really Want to LogOut");
        if(a==0){
            new index().setVisible(true);
        
        
        }
        else
            
         setVisible(true);;
    }//GEN-LAST:event_logOutActionPerformed

    private void saveMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMarkActionPerformed
        // TODO add your handling code here:
        String rollno =rollNo.getText();
        String english =subEng.getText();
        String mathematics=subMath.getText();
        String physics=subPhysics.getText();
        String chemistry=subChemistry.getText();
        String enggDrawing =subDrawing.getText();
        
        if(rollno.equals("")||!english.equals("")||!mathematics.equals("")
                |!physics.equals("")||!chemistry.equals("")||!enggDrawing.equals(""))
              rlab.setText("Roll no can't be Empty");
       if(!rollno.equals("")||english.equals("")||!mathematics.equals("")
                |!physics.equals("")||!chemistry.equals("")||!enggDrawing.equals(""))
              jLabel1.setText("marks can't be empty");
      if(!rollno.equals("")||!english.equals("")||mathematics.equals("")
                |!physics.equals("")||!chemistry.equals("")||!enggDrawing.equals(""))
              jLabel2.setText("marks can't be empty");
        if(!rollno.equals("")||!english.equals("")||!mathematics.equals("")
                |physics.equals("")||!chemistry.equals("")||!enggDrawing.equals(""))
              jLabel3.setText("marks can't be empty");
        if(!rollno.equals("")||!english.equals("")||!mathematics.equals("")
                |!physics.equals("")||chemistry.equals("")||!enggDrawing.equals(""))
              jLabel4.setText("marks can't be empty");
        if(!rollno.equals("")||!english.equals("")||!mathematics.equals("")
                |!physics.equals("")||!chemistry.equals("")||enggDrawing.equals(""))
              jLabel5.setText("marks can't be empty");
        
         try{
          Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","210396");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student where rollno='"+rollno+"'");
            if(rs.next()){
            st.executeUpdate("insert into marks values('"+rollno+"','"+english+"','"+mathematics+"','"+physics+"','"+chemistry+"','"+enggDrawing+"')");
            JOptionPane.showMessageDialog(null,"Sucessfully added");
        
      }
            else{
                JOptionPane.showMessageDialog(null,"Result not in Database");
            }
         }
    catch(Exception e){
JOptionPane.showMessageDialog(null, e.toString());
   }
       
    }//GEN-LAST:event_saveMarkActionPerformed

    private void rollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rollNoActionPerformed

    private void subEngKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subEngKeyPressed
        // TODO add your handling code here:
        String PATTERN ="^[0-9]";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(subEng.getText());
        if(!match.matches()||subEng.getText().length()>3)
       { jLabel1.setText("Invalid Mark");}
        else
        {jLabel1.setText(null);}
        
    }//GEN-LAST:event_subEngKeyPressed

    private void subMathKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subMathKeyPressed
        // TODO add your handling code here:
        String PATTERN ="^[0-9]$";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(subMath.getText());
        if(!match.matches()||subMath.getText().length()>3)
       { jLabel2.setText("Invalid Mark");}
         if(subMath.getText().length()<=3&&subMath.getText().length()>0)
        {jLabel2.setText(null);}
        
    }//GEN-LAST:event_subMathKeyPressed

    private void subPhysicsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subPhysicsKeyPressed
        // TODO add your handling code here:
        String PATTERN ="^[0-9]$";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(subPhysics.getText());
        if(!match.matches()||(subPhysics.getText().length()>3))
       { jLabel3.setText("Invalid Mark");}
        else
        {jLabel3.setText(null);}
    }//GEN-LAST:event_subPhysicsKeyPressed

    private void subChemistryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subChemistryKeyPressed
        // TODO add your handling code here:
        String PATTERN ="^[0-9]";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(subChemistry.getText());
        if(!match.matches()||subChemistry.getText().length()>3)
       { jLabel4.setText("Invalid Mark");}
        else
        {jLabel4.setText(null);}
    }//GEN-LAST:event_subChemistryKeyPressed

    private void subDrawingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subDrawingKeyPressed
        // TODO add your handling code here:
        String PATTERN ="^[0-9]";
        Pattern patt =Pattern.compile(PATTERN);
        Matcher match =patt.matcher(subDrawing.getText());
        if(!match.matches()||subDrawing.getText().length()>3)
       { jLabel5.setText("Invalid Mark");}
        else
        {jLabel5.setText(null);}
    }//GEN-LAST:event_subDrawingKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JButton allStudent;
    private javax.swing.JButton insertResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton logOut;
    private javax.swing.JButton regStudent;
    private javax.swing.JLabel rlab;
    private javax.swing.JTextField rollNo;
    private javax.swing.JButton saveMark;
    private javax.swing.JTextField subChemistry;
    private javax.swing.JTextField subDrawing;
    private javax.swing.JTextField subEng;
    private javax.swing.JTextField subMath;
    private javax.swing.JTextField subPhysics;
    // End of variables declaration//GEN-END:variables
}
