/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementportal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sandy
 */
public class resultStudent extends javax.swing.JFrame {

    /**
     * Creates new form resultStudent
     */
    public resultStudent() {
        initComponents();
    }
    
     public resultStudent(String rollno) {
        initComponents();
        
        rollNo.setText(rollno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rollNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textBranch = new javax.swing.JTextField();
        textCourse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textGender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFather = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        totalMarks = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        securedMark = new javax.swing.JTextField();
        passFailStatus = new javax.swing.JTextField();
        greetings = new javax.swing.JTextField();
        viewAnother = new javax.swing.JButton();
        back = new javax.swing.JButton();
        markChem = new javax.swing.JTextField();
        markDrawing = new javax.swing.JTextField();
        markPhy = new javax.swing.JTextField();
        markEng = new javax.swing.JTextField();
        markMth = new javax.swing.JTextField();
        passMarkMth = new javax.swing.JTextField();
        passMarkPhy = new javax.swing.JTextField();
        passMarkChem = new javax.swing.JTextField();
        passMarkEng = new javax.swing.JTextField();
        passMarkED = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        star = new javax.swing.JTextField();
        star2 = new javax.swing.JTextField();
        star3 = new javax.swing.JTextField();
        star4 = new javax.swing.JTextField();
        star5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 10));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        textName.setEditable(false);
        textName.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setText("Roll no");

        rollNo.setEditable(false);
        rollNo.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        rollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setText("Branch");

        textBranch.setEditable(false);
        textBranch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        textBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBranchActionPerformed(evt);
            }
        });

        textCourse.setEditable(false);
        textCourse.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setText("Course");

        textGender.setEditable(false);
        textGender.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        textGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGenderActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        textFather.setEditable(false);
        textFather.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setText("Father's Name");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setText("Total marks");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 368, 115, 28));

        totalMarks.setEditable(false);
        totalMarks.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        totalMarks.setText("500");
        jPanel1.add(totalMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 371, 62, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setText("Physics");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 156, 115, 28));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField10.setText("100");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 265, 62, -1));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField7.setText("100");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 212, 62, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setText("Mathematics");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 103, 115, 28));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setText("Chemistry");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 209, 115, 28));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField9.setText("100");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 106, 62, -1));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField11.setText("100");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 318, 62, -1));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextField8.setText("100");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 159, 62, -1));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel11.setText("Engg. Drawing");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 315, 115, 28));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel10.setText("English");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 262, 115, 28));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel13.setText("Marks Secured");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 421, 115, 28));

        securedMark.setEditable(false);
        securedMark.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        securedMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securedMarkActionPerformed(evt);
            }
        });
        jPanel1.add(securedMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 424, 62, -1));

        passFailStatus.setEditable(false);
        passFailStatus.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        passFailStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFailStatusActionPerformed(evt);
            }
        });
        jPanel1.add(passFailStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 505, 220, -1));

        greetings.setEditable(false);
        greetings.setBackground(new java.awt.Color(255, 153, 153));
        greetings.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        greetings.setBorder(null);
        greetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greetingsActionPerformed(evt);
            }
        });
        jPanel1.add(greetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 516, 300, 44));

        viewAnother.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        viewAnother.setText("View Another");
        viewAnother.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        viewAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnotherActionPerformed(evt);
            }
        });
        jPanel1.add(viewAnother, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 624, 123, 37));

        back.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementportal/logo/back (1).png"))); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 624, 72, 37));

        markChem.setEditable(false);
        markChem.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        markChem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markChemActionPerformed(evt);
            }
        });
        jPanel1.add(markChem, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 212, 42, -1));

        markDrawing.setEditable(false);
        markDrawing.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        markDrawing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDrawingActionPerformed(evt);
            }
        });
        jPanel1.add(markDrawing, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 318, 42, -1));

        markPhy.setEditable(false);
        markPhy.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        markPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markPhyActionPerformed(evt);
            }
        });
        jPanel1.add(markPhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 159, 42, -1));

        markEng.setEditable(false);
        markEng.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        markEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markEngActionPerformed(evt);
            }
        });
        jPanel1.add(markEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 265, 42, -1));

        markMth.setEditable(false);
        markMth.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        markMth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markMthActionPerformed(evt);
            }
        });
        jPanel1.add(markMth, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 106, 42, -1));

        passMarkMth.setEditable(false);
        passMarkMth.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        passMarkMth.setText("40");
        passMarkMth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passMarkMthActionPerformed(evt);
            }
        });
        jPanel1.add(passMarkMth, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 106, 42, -1));

        passMarkPhy.setEditable(false);
        passMarkPhy.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        passMarkPhy.setText("40");
        passMarkPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passMarkPhyActionPerformed(evt);
            }
        });
        jPanel1.add(passMarkPhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 159, 42, -1));

        passMarkChem.setEditable(false);
        passMarkChem.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        passMarkChem.setText("40");
        passMarkChem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passMarkChemActionPerformed(evt);
            }
        });
        jPanel1.add(passMarkChem, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 212, 42, -1));

        passMarkEng.setEditable(false);
        passMarkEng.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        passMarkEng.setText("40");
        passMarkEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passMarkEngActionPerformed(evt);
            }
        });
        jPanel1.add(passMarkEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 265, 42, -1));

        passMarkED.setEditable(false);
        passMarkED.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        passMarkED.setText("40");
        passMarkED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passMarkEDActionPerformed(evt);
            }
        });
        jPanel1.add(passMarkED, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 318, 42, -1));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel14.setText("Full mark");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 53, -1, -1));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel15.setText("Pass Mark");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 53, -1, -1));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel16.setText("Secured mark");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 53, -1, -1));

        star.setBackground(new java.awt.Color(255, 153, 153));
        star.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star.setBorder(null);
        jPanel1.add(star, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 50, -1));

        star2.setBackground(new java.awt.Color(255, 153, 153));
        star2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star2.setBorder(null);
        jPanel1.add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 50, -1));

        star3.setBackground(new java.awt.Color(255, 153, 153));
        star3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star3.setBorder(null);
        jPanel1.add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 50, -1));

        star4.setBackground(new java.awt.Color(255, 153, 153));
        star4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star4.setBorder(null);
        jPanel1.add(star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 50, -1));

        star5.setBackground(new java.awt.Color(255, 153, 153));
        star5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star5.setBorder(null);
        star5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star5ActionPerformed(evt);
            }
        });
        jPanel1.add(star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rollNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textBranch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCourse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textGender))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFather)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(textBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(textCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(textGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(textFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 309, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBranchActionPerformed

    private void textGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textGenderActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void viewAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnotherActionPerformed
        // TODO add your handling code here:
        setVisible(false);
     new studentSection().setVisible(true);
    }//GEN-LAST:event_viewAnotherActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
      new index().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void greetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greetingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greetingsActionPerformed

    private void markChemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markChemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markChemActionPerformed

    private void markDrawingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDrawingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markDrawingActionPerformed

    private void markPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markPhyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markPhyActionPerformed

    private void markEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markEngActionPerformed

    private void markMthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markMthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markMthActionPerformed

    private void rollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoActionPerformed
        // TODO add your handling code here:
         
    
    }//GEN-LAST:event_rollNoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String rollno=rollNo.getText();
       try{
          Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","210396");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student inner join marks where student.rollno='"+rollno+"' and    marks.rollno='"+rollno+"' ");

            if(rs.next()){
                textName.setText(rs.getString(4));
                
                textBranch.setText(rs.getString(3));
                textGender.setText(rs.getString(5));
                textFather.setText(rs.getString(6));
                textCourse.setText(rs.getString(2));
                
         // subject Marks of subjects
         markMth.setText(rs.getString(9));
         markPhy.setText(rs.getString(10));
         markChem.setText(rs.getString(11));
         markEng.setText(rs.getString(8));
         markDrawing.setText(rs.getString(12));
        
        
        
        int mark1=Integer.parseInt(markPhy.getText());
        int mark2=Integer.parseInt(markMth.getText());
        int mark3=Integer.parseInt(markChem.getText());
        int mark4=Integer.parseInt(markEng.getText());
        int mark5=Integer.parseInt(markDrawing.getText());
               
       int achievedMarks=mark1+mark2+mark3+mark4+mark5;
               
        securedMark.setText(String.valueOf(achievedMarks));
        if(mark1<40||mark2<40||mark3<40||mark4<40||mark5<40)
        {passFailStatus.setText("Fail");
        greetings.setText("Sorry , Try Again");}
        else
        {passFailStatus.setText("Pass");
        greetings.setText("Congratulations");
        }
        
        
        
        int percentage= (( achievedMarks/100)*100);
        
      


      mark1=Integer.parseInt(markPhy.getText());
          if(mark1<40)
              star.setText("*");
        mark2=Integer.parseInt(markMth.getText());
            if(mark2<40)
              star2.setText("*");
        mark3=Integer.parseInt(markChem.getText());
            if(mark3<40)
              star3.setText("*");
         mark4=Integer.parseInt(markEng.getText());
           if(mark4<40)
              star4.setText("*");
         mark5=Integer.parseInt(markDrawing.getText());
            if(mark5<40)
              star5.setText("*");
               
      }
       }
    catch(Exception e){
JOptionPane.showMessageDialog(null, e.toString());
   }
    }//GEN-LAST:event_formComponentShown

    private void passMarkMthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passMarkMthActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passMarkMthActionPerformed

    private void passMarkPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passMarkPhyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passMarkPhyActionPerformed

    private void passMarkChemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passMarkChemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passMarkChemActionPerformed

    private void passMarkEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passMarkEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passMarkEngActionPerformed

    private void passMarkEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passMarkEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passMarkEDActionPerformed

    private void securedMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securedMarkActionPerformed
        // TODO add your handling code here:
              
        
    }//GEN-LAST:event_securedMarkActionPerformed

    private void passFailStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFailStatusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passFailStatusActionPerformed

    private void star5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_star5ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField greetings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField markChem;
    private javax.swing.JTextField markDrawing;
    private javax.swing.JTextField markEng;
    private javax.swing.JTextField markMth;
    private javax.swing.JTextField markPhy;
    private javax.swing.JTextField passFailStatus;
    private javax.swing.JTextField passMarkChem;
    private javax.swing.JTextField passMarkED;
    private javax.swing.JTextField passMarkEng;
    private javax.swing.JTextField passMarkMth;
    private javax.swing.JTextField passMarkPhy;
    private javax.swing.JTextField rollNo;
    private javax.swing.JTextField securedMark;
    private javax.swing.JTextField star;
    private javax.swing.JTextField star2;
    private javax.swing.JTextField star3;
    private javax.swing.JTextField star4;
    private javax.swing.JTextField star5;
    private javax.swing.JTextField textBranch;
    private javax.swing.JTextField textCourse;
    private javax.swing.JTextField textFather;
    private javax.swing.JTextField textGender;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField totalMarks;
    private javax.swing.JButton viewAnother;
    // End of variables declaration//GEN-END:variables
}
